[[plugins]]
repo = 'Shougo/dein.vim'

# ------------------------------------
# colorscheme tender setting
# ------------------------------------
[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
    colorscheme tender
    set background=dark
    syntax on
    set t_Co=256
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
'''

# ------------------------------------
# Git vim-fugitive
# ------------------------------------
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
    nnoremap <silent> gs :Gstatus<CR><C-w>T
    nnoremap <silent> gps :Gpush<CR>
    nnoremap <silent> gpl :Gpull<CR>
'''
